apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundry.fullname" . }}-keycloak-config-cli
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
data:
  realm.json: |
    {
      "realm": "master",

      "clientScopes": [
        {
          "name": "topomojo-api",
          "description": "TopoMojo API",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "true",
            "display.on.consent.screen": "true"
          },
          "protocolMappers": [
            {
              "name": "audiences",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "topomojo-api",
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            },
            {
              "name": "subject",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-sub-mapper",
              "consentRequired": false,
              "config": {
                "access.token.claim": "true",
                "id.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ]
        },
        {
          "name": "gameboard-api",
          "description": "Gameboard API",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "true",
            "display.on.consent.screen": "true"
          },
          "protocolMappers": [
            {
              "name": "audiences",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "gameboard-api",
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            },
            {
              "name": "subject",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-sub-mapper",
              "consentRequired": false,
              "config": {
                "access.token.claim": "true",
                "id.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],

      "clients": [
        {
          "clientId": "topomojo-client",
          "name": "TopoMojo",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "redirectUris": [
            "/oidc",
            "/oidc-silent.html"
          ],
          "rootUrl": "https://{{ .Values.global.domain }}/topomojo",
          "defaultClientScopes": ["openid", "profile", "topomojo-api"],
          "attributes": {
            "pkce.code.challenge.method": "S256",
          }
        },
        {
          "clientId": "topomojo-swagger",
          "name": "TopoMojo Swagger",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "redirectUris": ["/oauth2-redirect.html"],
          "rootUrl": "https://{{ .Values.global.domain }}/topomojo/api",
          "defaultClientScopes": ["openid", "profile", "topomojo-api"],
          "attributes": {
            "consent.required": "true",
          }
        },
        {
          "clientId": "gameboard-client",
          "name": "Gameboard",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "redirectUris": [
            "/oidc",
            "/oidc-silent.html"
          ],
          "rootUrl": "https://{{ .Values.global.domain }}/gameboard",
          "defaultClientScopes": [
            "openid",
            "profile",
            "organization",
            "gameboard-api"
          ],
          "attributes": {
            "pkce.code.challenge.method": "S256",
          }
        },
        {
          "clientId": "gameboard-swagger",
          "name": "Gameboard Swagger",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "redirectUris": [
            "/oauth2-redirect.html"
          ],
          "rootUrl": "https://{{ .Values.global.domain }}/gameboard/api",
          "defaultClientScopes": ["openid", "profile", "gameboard-api"],
          "attributes": {
            "consent.required": "true",
          }
        },
        {
          "clientId": "gitea-client",
          "name": "Gitea",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "a92de95c865db308dfa5b7a098f45a7f",
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "implicitFlowEnabled": false,
          "redirectUris": [
            "/user/oauth2/Foundry/callback"
          ],
          "rootUrl": "https://{{ .Values.global.domain }}/gitea",
          "defaultClientScopes": ["openid", "profile", "email"],
          "attributes": {
            "oauth2.device.authorization.grant.enabled": "false"
          }
        }
      ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundry.fullname" . }}-gitea-env
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
data:
  GITEA__OAUTH2_CLIENT__OPENID_CONNECT_SCOPES: profile email
  GITEA__OAUTH2_CLIENT__ENABLE_AUTO_REGISTRATION: "true"
  GITEA__OAUTH2_CLIENT__USERNAME: userid
  GITEA__OAUTH2_CLIENT__ACCOUNT_LINKING: auto
