apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundry.fullname" . }}-gitea-env
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
data:
  GITEA__OAUTH2_CLIENT__OPENID_CONNECT_SCOPES: profile email
  GITEA__OAUTH2_CLIENT__ENABLE_AUTO_REGISTRATION: "true"
  GITEA__OAUTH2_CLIENT__USERNAME: userid
  GITEA__OAUTH2_CLIENT__ACCOUNT_LINKING: auto

---
{{- $binaryExt := list "png" "jpg" "jpeg" "gif" "bmp" "ico" "zip" "tar" "gz" "tgz" "pdf" "bin" }}
{{- $textData := dict -}}
{{- $binData  := dict -}}

{{- range $path, $_ := .Files.Glob "files/mkdocs/**" }}
  {{- $key := replace "/" "__" $path }}
  {{- $ext := trimPrefix "." (lower (ext $path)) }}
  {{- $contents := $.Files.Get $path }}
  {{- if has $ext $binaryExt }}
        {{- $_ := set $binData  $key ($contents | b64enc) }}
  {{- else }}
        {{- $_ := set $textData $key ($contents | toString) }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundry.fullname" . }}-mkdocs-files
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
binaryData:
{{- range $k, $v := $binData }}
  {{ $k }}: {{ $v }}
{{- end }}
data:
{{- range $k, $v := $textData }}
  {{ $k }}: |-
{{ (tpl $v $) | indent 4 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundry.fullname" . }}-gitea-job-script
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
data:
  seed-gitea.sh: |
    #!/bin/sh
    set -e

    GITEA_URL=http://{{ include "foundry.fullname" . }}-gitea
    GITEA_ADMIN_USERNAME={{ .Values.gitea.adminUsername }}

    # Wait for Gitea to be ready
    echo "Waiting for Gitea to be ready..."
    until wget -q --spider "${GITEA_URL}/api/v1/version"; do
      echo "Gitea is not ready yet. Waiting..."
      sleep 5
    done
    echo "Gitea is ready!"

    CREATE_ORG_RESPONSE=$(wget -q -O - \
      --header="Content-Type: application/json" \
      --header="Authorization: Basic $(echo -n ${GITEA_ADMIN_USERNAME}:${GITEA_ADMIN_PASSWORD} | base64)" \
      --post-data="{
        \"username\": \"${GITEA_ADMIN_USERNAME}-test\",
        \"repo_admin_change_team_access\": true
      }" \
      "${GITEA_URL}/api/v1/orgs" 2>&1) || {
        echo "Failed to create organization. Response: ${CREATE_ORG_RESPONSE}"

        # Check if org already exists
        if echo "${CREATE_ORG_RESPONSE}" | grep -q "422"; then
          echo "Organization already exists. Proceeding with repo creation..."
        else
          exit 1
        fi
      }

    echo "Organization created."

    CREATE_REPO_RESPONSE=$(wget -q -O - \
      --header="Content-Type: application/json" \
      --header="Authorization: Basic $(echo -n ${GITEA_ADMIN_USERNAME}:${GITEA_ADMIN_PASSWORD} | base64)" \
      --post-data="{
        \"name\": \"mkdocs\",
        \"private\": false,
        \"default_branch\": \"main\"
      }" \
      "${GITEA_URL}/api/v1/user/repos" 2>&1) || {
        echo "Failed to create repository. Response: ${CREATE_REPO_RESPONSE}"

        # Check if repo already exists
        if echo "${CREATE_REPO_RESPONSE}" | grep -q "409"; then
          echo "Repository already exists. Proceeding with push..."
        else
          exit 1
        fi
      }

    echo "Repository created or already exists."

    # Check if repository is empty before committing
    REPO_URL="http://$GITEA_ADMIN_USERNAME:$GITEA_ADMIN_PASSWORD@{{ include "foundry.fullname" . }}-gitea/foundry/mkdocs.git"

    echo "Checking if repository is empty..."
    REMOTE_REFS=$(git ls-remote "$REPO_URL" 2>/dev/null || echo "")

    if [ -n "$REMOTE_REFS" ]; then
      echo "Repository is not empty. Skipping initial commit."
      exit 0
    fi

    echo "Repository is empty. Proceeding with initial commit..."

    # Set git user vars
    git config --global user.name "Foundry Administrator"
    git config --global user.email "administrator@foundry.local"
    git config --global init.defaultBranch main

    cp -RL /mkdocs /tmp
    git -C /tmp/mkdocs init
    git -C /tmp/mkdocs add -A
    git -C /tmp/mkdocs commit -m "Initial commit"
    git -C /tmp/mkdocs push -u http://$GITEA_ADMIN_USERNAME:$GITEA_ADMIN_PASSWORD@{{ include "foundry.fullname" . }}-gitea/foundry/mkdocs.git --all
