kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "foundry.fullname" . }}-topomojo-nfs
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
