{{- $postgresqlSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-postgresql" (include "foundry.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundry.fullname" . }}-postgresql
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  postgres-password: {{ if $postgresqlSecret }}{{ index $postgresqlSecret.data "postgres-password" }}{{ else }}{{ randAlphaNum 16 | b64enc | quote }}{{ end }}

---
{{- $giteaSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-gitea-admin-secret" (include "foundry.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundry.fullname" . }}-gitea-admin-secret
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "gitea_admin" | b64enc | quote }}
  password: {{ if $giteaSecret }}{{ index $giteaSecret.data "password" }}{{ else }}{{ randAlphaNum 16 | b64enc | quote }}{{ end }}
