apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundry.fullname" . }}-credentials
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.credentials.postgresPassword | b64enc | quote }}
