#!/bin/bash
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.


if git rev-parse --git-dir > /dev/null 2>&1; then
    VERSION_TAG=$(git tag --points-at HEAD 'v*')
    GIT_BRANCH=$(git branch --show-current)
    GIT_HASH=$(git rev-parse --short HEAD)
fi

if [ -n "$VERSION_TAG" ]; then
    BUILD_VERSION=$VERSION_TAG
elif [ -n "$GIT_HASH" ]; then
    BUILD_VERSION=$GIT_BRANCH-$GIT_HASH
else
    BUILD_VERSION="Custom Build [$(date)]"
fi

packer build -var "appliance_version=$BUILD_VERSION" $@ foundry-appliance.json
