#!/bin/bash 
# Change to the current directory
DIRECTORY="$(dirname "${BASH_SOURCE[0]}")"
cd $DIRECTORY
helm delete topomojo|| true 
helm delete gameboard || true
helm delete alloy || true 
helm delete caster || true 
helm delete code-server || true 
helm delete gitea || true 
helm delete gitlab || true 
helm delete identity || true 
helm delete kubernetes-dashboard || true 
helm delete player || true 
helm delete steamfitter || true 
helm delete staticweb || true
helm delete stackstorm || true
helm delete mongodb || true
echo "Sleeping for 60 seconds"
sleep 60
helm delete postgresql || true 
helm delete nfs-server-provisioner || true 
echo "Sleeping for 30 seconds"
sleep 30
kubectl delete pvc --all
kubectl delete configmap --all
kubectl delete secret --all
kubectl delete job --all
