#!/bin/bash 
# Change to the current directory
DIRECTORY="$(dirname "${BASH_SOURCE[0]}")"
cd $DIRECTORY
# Remove common apps 
kubectl config set-context --current --namespace=common
helm delete code-server || true 
helm delete gitea || true 
helm delete identity || true 
helm delete kubernetes-dashboard || true 
helm delete mkdocs-material || true
helm delete pgadmin4 || true
helm delete keycloak || true
#Remove Crucible apps
kubectl config set-context --current --namespace=crucible
helm delete alloy || true 
helm delete caster || true 
helm delete player || true 
helm delete steamfitter || true 
helm delete gitlab || true 
helm delete stackstorm-ha || true
helm delete mongodb || true
# Remove Topomojo apps
kubectl config set-context --current --namespace=topomojo
helm delete topomojo|| true 
helm delete gameboard || true
kubectl delete pvc --all


echo "Waiting or pods to terminate - Sleeping for 20 seconds"
sleep 20
kubectl config set-context --current --namespace=common
helm delete postgresql || true 
helm delete nfs-server-provisioner || true 
helm delete ingress-nginx || true

echo "Waiting for storage to terminate - Sleeping for 20 seconds"
sleep 20 
echo " Cleaning up volumes, configmaps, secrets and jobs from all namespaces"
kubectl config set-context --current --namespace=common
kubectl delete pvc --all
#kubectl delete pvc -l name!=data-keycloak-postgresql-0 --all
kubectl delete configmap --all
kubectl delete secret --all
kubectl delete job --all

kubectl config set-context --current --namespace=crucible
kubectl delete pvc --all
kubectl delete configmap --all
kubectl delete secret --all
kubectl delete job --all

kubectl config set-context --current --namespace=topomojo
kubectl delete pvc --all
kubectl delete configmap --all
kubectl delete secret --all
kubectl delete job --all

echo "Cleaning up namespaces"
kubectl delete namespace crucible
#kubectl delete namespace common
kubectl delete namespace topomojo


