#!/bin/bash -xe
# Change to the current directory
DIRECTORY="$(dirname "${BASH_SOURCE[0]}")"
cd $DIRECTORY
apps="common,$1"
IFS=',' read -a stacks <<< $apps
echo "The following apps will be installed ${stacks[@]}"
# Always run common apps. 
for stack in ${stacks[@]}; do
  echo "Installing $stack with script located at $DIRECTORY/$stack/setup-$stack"
  $DIRECTORY/$stack/setup-$stack
done