apiVersion: v2
name: infra
description: Crucible appliance infrastructure and pre-created secrets
type: application
version: 0.0.0

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.20.0

  - name: nfs-server-provisioner
    repository: https://kvaps.github.io/charts
    version: 1.8.0
    condition: nfs-server-provisioner.enabled

  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.15.0
    condition: ingress-nginx.enabled

  - name: postgres
    alias: postgresql
    repository: https://self-hosters-by-night.github.io/helm-charts
    version: 0.14.2
    condition: postgresql.enabled
