apiVersion: v2
name: infra
description: Crucible appliance infrastructure (wraps sei/crucible-infra + cert-manager)
type: application
version: 0.0.0

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.20.0

  - name: crucible-infra
    repository: https://helm.cmusei.dev/charts
    version: 0.1.0
