apiVersion: v2
name: crucible
description: Crucible application stack (sei/crucible-apps + Gitea + MkDocs)
type: application
version: 0.0.0

dependencies:
  - name: crucible-apps
    repository: https://helm.cmusei.dev/charts
    version: 0.2.2

  - name: gitea
    version: 3.2.8

  - name: mkdocs-material
    repository: https://helm.cmusei.dev/charts
    version: 0.2.15
