apiVersion: v2
name: crucible
description: Crucible application stack (sei/crucible + Gitea + MkDocs)
type: application
version: 0.0.0

dependencies:
  - name: crucible
    alias: sei-crucible
    repository: https://helm.cmusei.dev/charts
    version: 0.1.3

  - name: gitea
    version: 3.2.8

  - name: mkdocs-material
    repository: https://helm.cmusei.dev/charts
    version: 0.2.15
