{{- if index .Values "nfs-server-provisioner" "enabled" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nfsVolumes.namePrefix }}-topomojo-api-nfs
  labels:
    {{- include "infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: topomojo-storage
    app.kubernetes.io/part-of: topomojo
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.nfsVolumes.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.topomojoSize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nfsVolumes.namePrefix }}-gameboard-api-nfs
  labels:
    {{- include "infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: gameboard-storage
    app.kubernetes.io/part-of: gameboard
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.nfsVolumes.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.gameboardSize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nfsVolumes.namePrefix }}-caster-api-nfs
  labels:
    {{- include "infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: caster-storage
    app.kubernetes.io/part-of: caster
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.nfsVolumes.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.casterSize }}
{{- end }}
