#!/bin/bash -e
#
# Copyright 2022 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.
#
# Foundry Appliance Install - Stage 2
#

# Generate SSH key
ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ''

# Generate CA and host certificates
~/foundry/certs/generate-certs -loglevel 3
