apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |
    .:53 {
      errors
      health {
        lameduck 5s
      }
      ready
      log . {
        class error
      }
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      hosts {
        $appliance_ip foundry.local gitlab.foundry.local
        fallthrough
      }
      prometheus :9153
      forward . $dns_server
      cache 30
      loop
      reload
      loadbalance
    } 
    