identity-api:

  replicaCount: 1

  image:
    repository: cmusei/identity
    tag: "1.4.7"

  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: foundry.local
        paths:
          - path: /identity
            pathType: ImplementationSpecific
    tls:
      - secretName: appliance-cert
        hosts:
          - foundry.local

  resources: {}
  #  limits:
  #    cpu: 200m
  #    memory: 256Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

  ## persistence; set existing pvc or size of new pvc
  storage:
    existing: ""
    size: "1Gi"
    mode: ReadWriteOnce
    class: local-path

  # Config app settings with environment vars.
  # Those most likely needing values are listed. For others,
  # see https://github.com/cmu-sei/Identity/blob/master/src/IdentityServer/appsettings.conf
  env:
    # Supported providers: InMemory, PostgreSQL, SqlServer
    Database__Provider: PostgreSQL
    Database__ConnectionString: Server=postgresql;Port=5432;Database=identity;Username=postgres;Password=foundry;SSL Mode=Prefer;Trust Server Certificate=true;
    Database__SeedFile: conf/seed.json
    Branding__ApplicationName: Foundry Identity
    Branding__UiHost: /identity/ui
    Branding__PathBase: /identity
    Account__Registration__AllowManual: true
    Account__Registration__AllowedDomains: foundry.local
    Cache__Key: idsrv
    Cache__RedisUrl: ""
    Cache__SharedFolder: ""
    Logging__Console__DisableColors: true
    Account__AdminEmail: "administrator@foundry.local"
    Account__AdminPassword: "foundry"
    Account__AdminGuid: "dee684c5-2eaf-401a-915b-d3d4320fe5d5"
    Account__OverrideCode: "123456"
    Account__Authentication__SigningCertificate: conf/signer.pfx
    Account__Authentication__SigningCertificatePassword: foundry
    Account__Authentication__NoticeFile: "conf/notice.html"
    AppMail__Url:
    AppMail__Key:
    AppMail__From:
#    Headers__Cors__Origins__0: "https://foundry.local"
#    Headers__Cors__Methods__0: "*"
#    Headers__Cors__Headers__0: "*"
#    Headers__Cors__AllowCredentials: true
    Headers__Forwarding__TargetHeaders: All
    Headers__Forwarding__KnownNetworks: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 ::ffff:a00:0/104 ::ffff:ac10:0/108 ::ffff:c0a8:0/112"
    Headers__Security__ContentSecurity: "default-src 'self'; script-src 'self' 'unsafe-inline'; frame-ancestors 'self';"

  conf:
    issuers: ""
    notice: ""
    terms: ""
    trouble: ""
    seed: |
      {
        "ApiResources": [
          {
            "Name": "gameboard-api",
            "DisplayName": "Gameboard API",
            "Enabled": true
          },
          {
            "Name": "topomojo-api",
            "DisplayName": "TopoMojo API",
            "Enabled": true
          }
        ],
        "Clients": [
          {
            "Name": "bootstrap-client",
            "DisplayName": "Bootstrap",
            "Enabled": true,
            "SeedGrant": "password",
            "SeedScopes": "openid profile topomojo-api",
            "SeedSecret": "foundry"
          },
          {
            "Name": "gameboard-client",
            "DisplayName": "Gameboard",
            "Enabled": true,
            "SeedFlags" : "Published, RequirePkce",
            "SeedGrant": "authorization_code",
            "SeedScopes": "openid profile gameboard-api",
            "Urls": [
              { "Type": "ClientUri", "Value": "https://foundry.local/gameboard" },
              { "Type": "RedirectUri", "Value": "https://foundry.local/gameboard/oidc" },
              { "Type": "RedirectUri", "Value": "https://foundry.local/gameboard/oidc-silent.html" },
              { "Type": "PostLogoutRedirectUri", "Value": "https://foundry.local/gameboard" }
            ]
          },
          {
            "Name": "gameboard-swagger",
            "DisplayName": "Gameboard Swagger",
            "Enabled": true,
            "SeedFlags" : "AllowRememberConsent",
            "SeedGrant": "authorization_code",
            "SeedScopes": "openid profile gameboard-api",
            "Urls": [
              { "Type": "ClientUri", "Value": "https://foundry.local/gameboard/api" },
              { "Type": "RedirectUri", "Value": "https://foundry.local/gameboard/api/oauth2-redirect.html" },
              { "Type": "PostLogoutRedirectUri", "Value": "https://foundry.local/gameboard/api" }
            ]
          },
          {
            "Name": "topomojo-client",
            "DisplayName": "TopoMojo",
            "Enabled": true,
            "SeedFlags" : "Published, RequirePkce",
            "SeedGrant": "authorization_code",
            "SeedScopes": "openid profile topomojo-api",
            "Urls": [
              { "Type": "ClientUri", "Value": "https://foundry.local/topomojo" },
              { "Type": "RedirectUri", "Value": "https://foundry.local/topomojo/oidc" },
              { "Type": "RedirectUri", "Value": "https://foundry.local/topomojo/oidc-silent.html" },
              { "Type": "PostLogoutRedirectUri", "Value": "https://foundry.local/topomojo" }
            ]
          },
          {
            "Name": "topomojo-swagger",
            "DisplayName": "TopoMojo Swagger",
            "Enabled": true,
            "SeedFlags" : "AllowRememberConsent",
            "SeedGrant": "authorization_code",
            "SeedScopes": "openid profile topomojo-api",
            "Urls": [
              { "Type": "ClientUri", "Value": "https://foundry.local/topomojo/api" },
              { "Type": "RedirectUri", "Value": "https://foundry.local/topomojo/api/oauth2-redirect.html" },
              { "Type": "PostLogoutRedirectUri", "Value": "https://foundry.local/topomojo/api" }
            ]
          }
        ]
      }
    signer: ""

identity-ui:

  replicaCount: 1

  image:
    repository: cmusei/identity-ui
    tag: "1.4.7"

  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: foundry.local
        paths:
          - path: /identity/ui
            pathType: ImplementationSpecific
    tls:
      - secretName: appliance-cert
        hosts:
          - foundry.local

  resources: {}
  #  limits:
  #    cpu: 20m
  #    memory: 20Mi
  #  requests:
  #    cpu: 20m
  #    memory: 20Mi

  basehref: /identity/ui

  settings: |
    {
      "apiUrl": "/identity",
      "applicationName": "Foundry Identity"
    }
