#!/bin/bash -xe
#
# Copyright 2022 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.

CURL_OPTS=( --silent --header "accept: application/json" --header "Content-Type: application/json" )
# Delete in case this is a re-run 
REQ=$( curl "${CURL_OPTS[@]}" \
                --user administrator:foundry \
                --request DELETE "https://$DOMAIN/gitea/api/v1/users/administrator/tokens/appliance-setup"
)
USER_TOKEN=$( curl "${CURL_OPTS[@]}" \
                --user administrator:foundry \
                --request POST "https://$DOMAIN/gitea/api/v1/users/administrator/tokens" \
                --data "{ \"name\": \"appliance-setup\"}" | jq -r '.sha1'
)

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"

# Set git user vars
git config --global user.name "Foundry Administrator"
git config --global user.email "administrator@$DOMAIN"

# Create foundry-docs organization
curl "${CURL_OPTS[@]}" \
  --request POST "https://$DOMAIN/gitea/api/v1/orgs?access_token=$USER_TOKEN" \
  --data @- <<EOF
{
  "username": "foundry",
  "repo_admin_change_team_access": true
}
EOF

# Create repo
curl "${CURL_OPTS[@]}" \
    --request POST "https://$DOMAIN/gitea/api/v1/orgs/foundry/repos?access_token=$USER_TOKEN" \
    --data @- <<EOF
{
  "name": "mkdocs",
  "private": false,
  "default_branch": "main"
}
EOF