apiVersion: v2
name: foundry
description: Foundry stack deployment

type: application
version: 0.1.0
appVersion: "0.10.0"

dependencies:
  - name: nfs-server-provisioner
    repository: https://kvaps.github.io/charts
    version: 1.8.0
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.12.2
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.6.7
  - name: pgadmin4
    repository: https://helm.runix.net
    version: 1.42.1
  - name: keycloak
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 24.6.4
  - name: gitea
    repository: https://dl.gitea.io/charts/
    version: 11.0.1
  - name: mkdocs-material
    repository: https://helm.cmusei.dev/charts
    version: 0.2.4
  - name: topomojo
    repository: file://../../../helm-charts/charts/topomojo
    version: 0.5.0
