  settingsYaml:
    appname: TopoMojo
    apphost: ""
    mkshost: ""
    oidc:
      authority: "https://foundry.local/auth/realms/master"
      client_id: "topomojo-client"
      redirect_uri: "https://foundry.local/topomojo/oidc"
      silent_redirect_uri: "https://foundry.local/topomojo/oidc-silent.html"
      post_logout_redirect_uri: "https://foundry.local/topomojo"
      response_type: "code"
      scope: "openid profile topomojo-api"
      automaticSilentRenew: true
      includeIdTokenInSilentRenew: false
      filterProtocolClaims: true
      loadUserInfo: true
      accessTokenExpiringNotificationTime: 120
      monitorSession: false
      useLocalStorage: true
