alloy-api:
  image:
    tag: '2.1.0'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: foundry.local
        paths:
          - /alloy/(api|swagger)
    tls:
      - secretName: appliance-cert
        hosts:
          - foundry.local

  env:
    CorsPolicy__Origins__0: https://foundry.local/alloy

    # Connection String to database
    ConnectionStrings__PostgreSQL: "Server=postgresql;Port=5432;Database=alloy_db;Username=postgres;Password='foundry';SSL Mode=Prefer;Trust Server Certificate=true;"

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://foundry.local/identity
    Authorization__AuthorizationUrl: https://foundry.local/identity/connect/authorize
    Authorization__AuthorizationScope: 'alloy-api player-api caster-api steamfitter-api vm-api'
    Authorization__ClientId: alloy-api
    Authorization__ClientName: 'Alloy API'

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://foundry.local/identity
    ResourceOwnerAuthorization__ClientId: alloy-api
    ResourceOwnerAuthorization__UserName: '' # TODO
    ResourceOwnerAuthorization__Password: '' # TODO
    ResourceOwnerAuthorization__Scope: 'alloy-api player-api caster-api steamfitter-api vm-api'

    # Crucible Application URLs
    ClientSettings__urls__playerApi: https://foundry.local/player
    ClientSettings__urls__casterApi: https://foundry.local/caster
    ClientSettings__urls__steamfitterApi: https://foundry.local/steamfitter

alloy-ui:
  image:
    tag: '2.2.0'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: foundry.local
        paths:
          - /alloy
    tls:
      - secretName: appliance-cert
        hosts:
          - foundry.local

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  # NOTE:  PlayerUIAddress is the URL to the Crucible - Player application
  settings: '{
    "ApiUrl": "https://foundry.local/alloy/api",
    "OIDCSettings": {
    "authority": "https://foundry.local/identity/",
    "client_id": "alloy-ui",
    "redirect_uri": "https://foundry.local/alloy/auth-callback",
    "post_logout_redirect_uri": "https://foundry.local/alloy",
    "response_type": "id_token token",
    "scope": "openid profile alloy-api player-api caster-api steamfitter-api vm-api",
    "automaticSilentRenew": true,
    "silent_redirect_uri": "https://foundry.local/alloy/auth-callback-silent"
    },
    "AppTitle": "Alloy",
    "AppTopBarText": "Alloy",
    "AppTopBarHexColor": "#b00",
    "PlayerUIAddress": "https://foundry.local/player/api",
    "UseLocalAuthStorage": true
    }'
