caster-api:
  image:
    tag: "2.1.1"
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: caster.crucible-dev.cmusei.dev
        paths:
        - /(api|swagger|hubs)
    tls:
      - secretName: crucible-dev-wildcard-cert
        hosts:
         - crucible-dev.cmusei.dev

  # Gets placed in /etc/gitconfig to allow immediate Gitlab access via access token
  # Replace TOKEN with an access token created in Gitlab, and update the Gitlab URL
  gitconfig: '[url "https://git-access-token:jgrR8jUdtWx2isMjyrHg@gitlab.crucible-dev.cmusei.dev/"]
        insteadOf = https://gitlab.crucible-dev.cmusei.dev/'

  # storage - either an existing pvc, the size for a new pvc, or emptyDir
  storage:
    existing: "appdata"
    size: ""
    mode: ReadWriteOnce
    class: default

  env:
    # This deployment comes built in with a script to install Terraform and the necessary
    # plugins to run Caster properly.  Internet access is required for this script to run properly.
    # It's recommended that this should remain false.  Please see the file "terraform-installation.tpl"
    # for more information on the installation process.
    SKIP_TERRAFORM_INSTALLATION: false

    VSPHERE_SERVER: ""
    VSPHERE_USER: ""
    VSPHERE_PASSWORD: ""
    VSPHERE_ALLOW_UNVERIFIED_SSL: true

    # See here for more information regarding AllowedHosts
    # https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hostfiltering.hostfilteringoptions.allowedhosts?view=aspnetcore-3.1
    AllowedHosts: "*"

    CorsPolicy__Origins__0: "https://caster.crucible-dev.cmusei.dev"

    ConnectionStrings__PostgreSQL: "Server=postgres;Port=5432;Database=crucible_dev_caster_db;Username=crucible_dev_caster_dbo@1ncu5k8s;Password='qzzlJgmKx6ZF4qlO1QfYJ92B31w0sxkq';SSL Mode=Prefer;Trust Server Certificate=true;"

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://id.crucible-dev.cmusei.dev
    Authorization__AuthorizationUrl: https://id.crucible-dev.cmusei.dev/connect/authorize
    Authorization__AuthorizationScope: "caster-api"
    Authorization__ClientId: caster-api

    # OAuth2 Identity Client /w Password
    Client__TokenUrl: https://id.crucible-dev.cmusei.dev/connect/token
    Client__ClientId: caster-admin
    Client__UserName: "caster.admin.user@crucible-dev.cmusei.dev"
    Client__Password: "321ChangeMe!"
    Client__Scope: "player-api vm-api"

    # Crucible Player URLs
    Player__VmApiUrl: "https://vm.crucible-dev.cmusei.dev"
    Player__VmConsoleUrl: "https://console.crucible-dev.cmusei.dev/vm/{id}/console"

    # Terraform Information
    # - DefaultVersion - The default version to be used.
    # - GitlabApiUrl - URL to the deployed Gitlab instance
    Terraform__DefaultVersion: "0.14.0"
    Terraform__GitlabApiUrl: "https://gitlab.crucible-dev.cmusei.dev/api/v4/"
    Terraform__GitlabToken: "wMa2RPQP_ZR3fxc5zQtv"
    Terraform__GitlabGroupId: 6

    # Configurable save lengths for Caster untagged versions
    FileVersions__DaysToSaveAllUntaggedVersions: 7
    FileVersions__DaysToSaveDailyUntaggedVersions: 31

    # Basic seed data to jumpstart deployement
    SeedData__Users__0__id: "9fd3c38e-58b0-4af1-80d1-1895af91f1f9"
    SeedData__Users__0__name:  "admin@crucible-dev.cmusei.dev"

    SeedData__Users__1__id:  "c4c631ca-3dbd-4d99-9c19-a8c3f7e5e493"
    SeedData__Users__1__name:  "caster.admin.user@crucible-dev.cmusei.dev"

    SeedData__UserPermissions__0__UserId:  "c4c631ca-3dbd-4d99-9c19-a8c3f7e5e493"
    SeedData__UserPermissions__0__PermissionId:  "00000000-0000-0000-0000-000000000001"
    SeedData__UserPermissions__1__UserId:  "9fd3c38e-58b0-4af1-80d1-1895af91f1f9"
    SeedData__UserPermissions__1__PermissionId:  "00000000-0000-0000-0000-000000000001"


caster-ui:
  image:
    tag: "2.2.1"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: caster.crucible-dev.cmusei.dev
        paths:
        - /
    tls:
      - secretName: crucible-dev-wildcard-cert
        hosts:
         - crucible-dev.cmusei.dev

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client
  settings: '{
    "ApiUrl": "https://caster.crucible-dev.cmusei.dev",
    "OIDCSettings": {
      "authority": "https://id.crucible-dev.cmusei.dev/",
      "client_id": "caster-ui",
      "redirect_uri": "https://caster.crucible-dev.cmusei.dev/auth-callback",
      "post_logout_redirect_uri": "https://caster.crucible-dev.cmusei.dev",
      "response_type": "id_token token",
      "scope": "openid profile email caster-api",
      "automaticSilentRenew": true,
      "silent_redirect_uri": "https://caster.crucible-dev.cmusei.dev/auth-callback-silent"
    },
    "UseLocalAuthStorage": true
  }'