apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
type: Opaque
stringData:
  initialRootPassword: foundry
  databasePassword: foundry
  minio: foundry
  backup: foundry
  provider: "{ 
    name: 'openid_connect',
    label: 'identity',
      args: {
        name: 'identity',
        scope: ['openid','profile','email'],
        response_type: 'code',
        issuer: 'https://foundry.local/identity',
        discovery: true,
        client_options: {
          identifier: 'gitlab',
          secret: '337bdcb1a23143a9b5a6aaa33c0e87d7',
          port: '443',
          scheme: 'https',
          host: 'foundry.local/identity',
          redirect_uri: 'https://gitlab.foundry.local/users/auth/identity/callback',
          end_session_endpoint: 'https://foundry.local/identity/connect/endsession'
        }
      }
    }"
