#!/bin/bash -x
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.

#############################
#   Crucible Stack Install   #
#############################

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"
root_dir=/home/foundr1y
# dependancy installs
./setup-gitlab

helm upgrade --wait --install -f mongodb.values.yaml mongodb bitnami/mongodb
if [ -f $root_dir/crucible/vcenter.env ]; then 
  import_vars $root_dir/crucible/vcenter.env
  # decrypt Password
  VSPHERE_PASS=$(decrypt_string $VSPHERE_PASS)
  envsubst < stackstorm-min.values.yaml | helm upgrade --wait --install --timeout 10m -f - stackstorm stackstorm/stackstorm-ha
else
  helm upgrade --wait --install --timeout 10m -f stackstorm-min.values.yaml stackstorm stackstorm/stackstorm-ha
fi
kubectl apply -f stackstorm-ingress.yaml

# Crucible Stack install
helm upgrade --wait --install -f player.values.yaml player ../charts/player 
helm upgrade --wait --install -f caster.values.yaml caster ../charts/caster

helm upgrade --wait --install -f steamfitter.values.yaml steamfitter ../charts/steamfitter
helm upgrade --wait --install -f alloy.values.yaml alloy ../charts/alloy
