#!/bin/bash -x
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.

#############################
#   Crucible Stack Install  #
#############################

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"
root_dir=/home/foundry
source ../scripts/utils
# dependancy installs
./setup-gitlab

helm_deploy --wait -u -p ../helm -f mongodb.values.yaml bitnami/mongodb
#helm upgrade --wait --install -f mongodb.values.yaml mongodb bitnami/mongodb
if [ -f $root_dir/crucible/vcenter.env ]; then 
  import_vars $root_dir/crucible/vcenter.env
  # decrypt Password
  VSPHERE_PASS=$(decrypt_string $VSPHERE_PASS)
  helm_deploy -r $root_dir/crucible/vcenter.env -u -p ../helm --version 0.80.0 --wait --timeout 10m -f stackstorm-min.values.yaml stackstorm/stackstorm-ha
  #envsubst < stackstorm-min.values.yaml | helm upgrade --wait --install --timeout 10m -f - stackstorm stackstorm/stackstorm-ha
else
  helm_deploy -u -p ../helm --wait --timeout 10m --version 0.80.0 -f stackstorm-min.values.yaml stackstorm/stackstorm-ha
  #helm upgrade --wait --install --timeout 10m -f stackstorm-min.values.yaml stackstorm stackstorm/stackstorm-ha
fi
kubectl apply -f stackstorm-ingress.yaml

# Crucible Stack install
helm_deploy -r ../appliance.vars -p ../helm -u -v 1.4.0 -f player.values.yaml sei/player
helm_deploy -r ../appliance.vars -p ../helm -u -v 1.4.0 -f caster.values.yaml sei/caster
helm_deploy -r ../appliance.vars -p ../helm -u -v 1.4.0 -f alloy.values.yaml sei/alloy
helm_deploy -r ../appliance.vars -p ../helm -u -v 1.4.0 -f steamfitter.values.yaml sei/steamfitter
#helm upgrade --wait --install -f player.values.yaml player ../charts/player 
#helm upgrade --wait --install -f caster.values.yaml caster ../charts/caster

#helm upgrade --wait --install -f steamfitter.values.yaml steamfitter ../charts/steamfitter
#helm upgrade --wait --install -f alloy.values.yaml alloy ../charts/alloy
