steamfitter-api:
  image:
    tag: "2.2.0"
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: steamfitter.crucible-dev.cmusei.dev
        paths:
        - /(api|swagger|hubs)
    tls:
      - secretName: crucible-dev-wildcard-cert
        hosts:
         - crucible-dev.cmusei.dev

  env:

    # Connection String to database
    ConnectionStrings__PostgreSQL: "Server=postgres;Port=5432;Database=crucible_dev_steamfitter_db;Username=crucible_dev_steamfitter_dbo@1ncu5k8s;Password='qzzlJgmKx6ZF4qlO1QfYJ92B31w0sxkq';SSL Mode=Prefer;Trust Server Certificate=true;"

    CorsPolicy__Origins__0: https://steamfitter.crucible-dev.cmusei.dev

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://id.crucible-dev.cmusei.dev
    Authorization__AuthorizationUrl: https://id.crucible-dev.cmusei.dev/connect/authorize
    Authorization__AuthorizationScope: "player-api steamfitter-api vm-api"
    Authorization__ClientId: steamfitter-api
    Authorization__ClientName: "Steamfitter API"

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://id.crucible-dev.cmusei.dev
    ResourceOwnerAuthorization__ClientId: steamfitter-api
    ResourceOwnerAuthorization__UserName: "" #TODO
    ResourceOwnerAuthorization__Password: "" #TODO
    ResourceOwnerAuthorization__Scope: "vm-api"

    ClientSettings__urls__playerApi: https://player.crucible-dev.cmusei.dev/
    ClientSettings__urls__vmApi: https://vm.crucible-dev.cmusei.dev/

    # Stackstorm Configuration
    # TODO - Document Stackstorm dependencies
    VmTaskProcessing__ApiType: st2
    VmTaskProcessing__ApiUsername: "st2admin"
    VmTaskProcessing__ApiPassword: "eYr#AxMS9@n6BsWWxPgj"
    VmTaskProcessing__ApiBaseUrl: "https://stackstorm.crucible-dev.cmusei.dev"
    VmTaskProcessing__ApiParameters__clusters: ""

    # Basic seed data to jumpstart deployement
    # TODO - Document Seed data
    # SeedData__Users__0__id: ""
    # SeedData__Users__0__name: ""

    # SeedData__Users__1__id: ""
    # SeedData__Users__1__name: ""

    # SeedData__UserPermissions__0__UserId: ""
    # SeedData__UserPermissions__0__PermissionId: ""
    # SeedData__UserPermissions__1__UserId: ""
    # SeedData__UserPermissions__1__PermissionId: ""

steamfitter-ui:
  image:
    tag: "2.2.0"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: steamfitter.crucible-dev.cmusei.dev
        paths:
        - /
    tls:
      - secretName: crucible-dev-wildcard-cert
        hosts:
         - crucible-dev.cmusei.dev

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client
  settings: '{
      "ApiUrl": "https://steamfitter.crucible-dev.cmusei.dev",
      "VmApiUrl": "https://vm.crucible-dev.cmusei.dev",
      "ApiPlayerUrl": "https://player.crucible-dev.cmusei.dev",
      "OIDCSettings": {
          "authority": "https://id.crucible-dev.cmusei.dev",
          "client_id": "steamfitter-ui",
          "redirect_uri": "https://steamfitter.crucible-dev.cmusei.dev/auth-callback",
          "post_logout_redirect_uri": "https://steamfitter.crucible-dev.cmusei.dev",
          "response_type": "id_token token",
          "scope": "openid profile player-api vm-api steamfitter-api",
          "automaticSilentRenew": true,
          "silent_redirect_uri": "https://steamfitter.crucible-dev.cmusei.dev/auth-callback-silent"
      },
      "UseLocalAuthStorage": true
  }'