replicaCount: 1

auth:
  adminUser: foundry
  adminPassword: foundry
postgresql:
  enabled: false
externalDatabase:
  host: postgresql
  port: 5432
  user: postgres
  database: keycloak
  password: foundry
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: foundry.local
  path: /auth
  tls: true
  extraTls:
    - hosts:
        - foundry.local
      secretName: appliance-cert
httpRelativePath: /auth/
