#!/bin/bash -e
#
# Copyright 2022 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.

#############################
#   Foundry Stack Install   #
#############################

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"

# Install NFS server
helm repo add kvaps https://kvaps.github.io/charts
helm install -f nfs-server-provisioner.values.yaml nfs-server-provisioner kvaps/nfs-server-provisioner
kubectl apply -f topomojo-pvc.yaml

# Install ingress-nginx
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm install ingress-nginx ingress-nginx/ingress-nginx \
             --wait \
             --values ingress/ingress-nginx.values.yaml \
             --namespace ingress \
             --create-namespace

# Add host certificate
kubectl create secret tls appliance-cert --key certs/host-key.pem --cert <( cat certs/host.pem certs/int-ca.pem )

# Install PostgreSQL
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install --wait -f postgresql.values.yaml postgresql bitnami/postgresql

# Install pgAdmin4
helm repo add runix https://helm.runix.net/
kubectl create secret generic pgpassfile --from-literal=pgpassfile=postgresql:5432:\*:postgres:foundry
helm install -f pgadmin4.values.yaml pgadmin4 runix/pgadmin4

# Install code-server (browser-based VS Code)
helm repo add nicholaswilde https://nicholaswilde.github.io/helm-charts/
helm install -f code-server.values.yaml code-server nicholaswilde/code-server

# Kubernetes Dashboard
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
helm install -f kubernetes-dashboard.values.yaml kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard

# Add root CA to chart values
ed -s mkdocs-material.values.yaml <<< $'/cacert:/s/\"\"/|-/\n/cacert:/r !sed "s/^/  /" certs/root-ca.pem\nw'
ed -s gameboard.values.yaml <<< $'/cacert:/s/\"\"/|-/\n/cacert:/r !sed "s/^/    /" certs/root-ca.pem\nw'
ed -s topomojo.values.yaml <<< $'/cacert.crt:/s/\"\"/|-/\n/cacert.crt:/r !sed "s/^/        /" certs/root-ca.pem\nw'
cp certs/root-ca.pem ../mkdocs/docs/root-ca.crt

# Install Gitea
git config --global init.defaultBranch main
helm repo add gitea https://dl.gitea.io/charts/
kubectl exec postgresql-0 -- psql 'postgresql://postgres:foundry@localhost' -c 'CREATE DATABASE gitea;'
helm install -f gitea.values.yaml gitea gitea/gitea
timeout 5m bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' https://foundry.local/gitea)" != "200" ]]; do sleep 5; done' || false
./setup-gitea

# Foundry Stack install
helm repo add sei https://helm.cyberforce.site/charts
helm install -f identity.values.yaml identity sei/identity
helm install -f mkdocs-material.values.yaml mkdocs-material sei/mkdocs-material
helm install --wait -f topomojo.values.yaml topomojo sei/topomojo
sleep 60

# Add bot user to TopoMojo
TOPOMOJO_ACCESS_TOKEN=$(curl --silent --request POST \
  --url 'https://foundry.local/identity/connect/token' \
  --data grant_type=password \
  --data client_id=bootstrap-client \
  --data client_secret=foundry \
  --data username=administrator@foundry.local \
  --data password=foundry | jq -r '.access_token')

USER_ID=$(curl -X POST --silent \
  --url "https://foundry.local/topomojo/api/user" \
  -H "Authorization: Bearer $TOPOMOJO_ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{ "name": "bot-gameboard", "role": "user", "scope": "gameboard" }' | jq -r '.id')

API_KEY=$(curl -X POST --silent \
  --url "https://foundry.local/topomojo/api/apikey/$USER_ID" \
  -H "Authorization: Bearer $TOPOMOJO_ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{}" | jq -r '.value')

sed -i -r "s/(Core__GameEngineClientSecret:).*/\1 $API_KEY/" gameboard.values.yaml

helm install --wait -f gameboard.values.yaml gameboard sei/gameboard
kubectl apply -f console-ingress.yaml

# Add administrator user to Gameboard
timeout 5m bash -c 'until kubectl exec postgresql-0 -- env PGPASSWORD=foundry psql -lqt -U postgres | cut -d \| -f 1 | grep -qw gameboard; do sleep 5; done' || false
sleep 5
kubectl exec postgresql-0 -- psql 'postgresql://postgres:foundry@localhost/gameboard' -c "INSERT INTO \"Users\" (\"Id\",\"Name\",\"ApprovedName\",\"Role\") VALUES ('dee684c5-2eaf-401a-915b-d3d4320fe5d5', 'Administrator', 'Administrator', 63);"

# Create git repo to track changes
git init
git add *
git commit -m "Initial commit"
