apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
type: Opaque
stringData:
  initialRootPassword: foundry
  databasePassword: foundry
  minio: foundry
  backup: foundry
  provider: |
    { 
      name: 'openid_connect',
      label: '$OAUTH_PROVIDER',
      args: {
      name: '$OAUTH_PROVIDER',
      scope: ['openid','profile','email'],
      response_type: 'code',
      issuer: 'https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORITY_URL',
      discovery: true,
        client_options: {
        identifier: 'gitlab',
        secret: 'FpKFczqaU9XQVATzVLWSUupCHlJVYOdL',
        port: '443',
        scheme: 'https',
        host: '$DOMAIN/$OAUTH_PROVIDER',
        redirect_uri: 'https://gitlab.$DOMAIN/users/auth/$OAUTH_PROVIDER/callback',
        end_session_endpoint: 'https://gitlab.$DOMAIN/$OAUTH_PROVIDER/connect/endsession'
        }
      }
    }
