# values-minikube.yaml
# This example intended as baseline to use Minikube for the deployment of GitLab
# - Minimized CPU/Memory load, can fit into 3 CPU, 6 GB of RAM (barely)
# - Services that are not compatible with how Minikube runs are disabled
# - Some services entirely removed, or scaled down to 1 replica.
# - Configured to use 192.168.99.100, and nip.io for the domain

# Minimal settings
global:
  image: 
    pullPolicy: IfNotPresent
  busybox:
    image:
      pullPolicy: IfNotPresent
    
  ingress:
    configureCertmanager: false
    class: "nginx"
    tls:
      enabled: true
      secretName: appliance-cert
  
  hosts:
    domain: foundry.local/gitlab
    externalIP:
    gitlab:
      name: gitlab.foundry.local
      https: true
    

  initialRootPassword: 
    secret: gitlab-secrets
    key: initialRootPassword
  
  psql:
    connectTimeout: 60
    password:
      useSecret: true
      secret: gitlab-secrets
      key: databasePassword
    host: postgresql.common.svc.cluster.local
    port: 5432
    username: postgres
    database: gitlab_db
    preparedStatements: false
  
  certificates:
    customCAs: 
      - secret: appliance-root-ca
      
  appConfig:
    object_store:
      enabled: false
    lfs:
      enabled: false
    artifacts:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    omniauth:
      enabled: true
      autoSignInWithProvider: identity
      syncProfileFromProvider: []
      syncProfileAttributes: ['email']
      allowSingleSignOn: true
      blockAutoCreatedUsers: false
      autoLinkLdapUser: false
      autoLinkSamlUser: false
      autoLinkUser: ['openid_connect', 'identity']
      externalProviders: []
      allowBypassTwoFactor: []
      providers: 
        - secret: gitlab-secrets
          key: provider

  
  minio:
    enabled: false
  # Disable Rails bootsnap cache (temporary)
  grafana:
    enabled: false

  rails:
    bootsnap:
      enabled: false
  shell:
    # Configure the clone link in the UI to include the high-numbered NodePort
    # value from below (`gitlab.gitlab-shell.service.nodePort`)
    port: 32022
# Don't use certmanager, we'll self-sign
certmanager:
  install: false
# Use the `ingress` addon, not our Ingress (can't map 22/80/443)
nginx-ingress:
  enabled: false
# Save resources, only 3 CPU
prometheus:
  install: false
gitlab-runner:
  install: false
postgresql:
  install: false
# Reduce replica counts, reducing CPU & memory requirements
gitlab:
  image:
    pullPolicy: IfNotPresent
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    # Map gitlab-shell to a high-numbered NodePort to support cloning over SSH since
    # Minikube takes port 22.
    service:
      type: NodePort
      nodePort: 32022
  toolbox:
    enabled: true
    replicas: 1
    antiAffinityLabels:
      matchLabels:
        app: 'gitaly'
    backups: 
      objectStorage: 
        backend: 's3'
        config:
          secret: gitlab-secrets
          key: backup
registry:
  enabled: false
