steamfitter-api:
  image:
    repository: cmusei/steamfitter-api
    tag: '3.6.1'
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: foundry.local
        paths:
          - path: /steamfitter/(api|swagger|hubs)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
         - foundry.local
  certificateMap: "appliance-root-ca"

  env:
    PathBase: "/steamfitter"
    # Connection String to database
    ConnectionStrings__PostgreSQL: "Server=postgresql.common.svc.cluster.local;Port=5432;Database=steamfitter_db;Username=postgres;Password=foundry;SSL Mode=Prefer;Trust Server Certificate=true;"

    CorsPolicy__Origins__0: https://foundry.local
    CorsPolicy__Origins__1: "http://localhost:4303"
    # CorsPolicy__AllowAnyOrigin: true
    CorsPolicy__AllowAnyMethod: true
    CorsPolicy__AllowAnyHeader: true

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://foundry.local/identity
    Authorization__AuthorizationUrl: https://foundry.local/identity/connect/authorize
    Authorization__TokenUrl: https://foundry.local/identity/connect/token
    Authorization__AuthorizationScope: "steamfitter-api vm-api player-api"
    Authorization__ClientId: steamfitter-api
    Authorization__ClientName: "Steamfitter API"

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://foundry.local/identity
    ResourceOwnerAuthorization__ClientId: steamfitter-admin
    ResourceOwnerAuthorization__UserName: crucible-admin@foundry.local #TODO
    ResourceOwnerAuthorization__Password: foundry #TODO
    ResourceOwnerAuthorization__Scope: "vm-api player-api"

    ClientSettings__urls__steamfitterApi: https://foundry.local/steamfitter
    ClientSettings__urls__vmApi: https://foundry.local/vm
    ClientSettings__urls__playerApi: https://foundry.local/player

    # Stackstorm Configuration
    # TODO - Document Stackstorm dependencies
    VmTaskProcessing__ApiType: st2
    VmTaskProcessing__ApiUsername: "administrator"
    VmTaskProcessing__ApiPassword: "foundry"
    VmTaskProcessing__ApiBaseUrl: "https://foundry.local/stackstorm/"
    VmTaskProcessing__ApiParameters__clusters: ""

    # Basic seed data to jumpstart deployement
    # TODO - Document Seed data
    SeedData__Users__0__id: "dee684c5-2eaf-401a-915b-d3d4320fe5d5"
    SeedData__Users__0__name:  "administrator@foundry.local"

    # SeedData__Users__1__id:  "3b680d97-6d0b-44c9-8cc7-fd10ea79c2a6"
    # SeedData__Users__1__name:  "caster-admin@foundry.local"

    SeedData__UserPermissions__0__UserId: "dee684c5-2eaf-401a-915b-d3d4320fe5d5"
    SeedData__UserPermissions__0__PermissionId: "00000000-0000-0000-0000-000000000001"
    # SeedData__UserPermissions__1__UserId: ""
    # SeedData__UserPermissions__1__PermissionId: ""

steamfitter-ui:
  image:
    repository: cmusei/steamfitter-ui
    pullPolicy: IfNotPresent
    tag: "3.6.1"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: public
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
        - host: foundry.local
          paths:
            - path: "/steamfitter(/|$)(.*)"
              pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
        - foundry.local
  env: 
    ## basehref is path to the app
    APP_BASEHREF: "/steamfitter"

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client
  settings: |- 
    {
      "ApiUrl": "https://foundry.local/steamfitter",
      "VmApiUrl": "https://foundry.local/vm",
      "ApiPlayerUrl": "https://foundry.local/player",
      "OIDCSettings": {
          "authority": "https://foundry.local/identity",
          "client_id": "steamfitter-ui",
          "redirect_uri": "https://foundry.local/steamfitter/auth-callback",
          "post_logout_redirect_uri": "https://foundry.local/steamfitter",
          "response_type": "code",
          "scope": "openid profile steamfitter-api vm-api player-api",
          "automaticSilentRenew": true,
          "silent_redirect_uri": "https://foundry.local/steamfitter/auth-callback-silent"
      },
      "UseLocalAuthStorage": true
    }